services:
  - type: web
    name: skillsync-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
      - key: GITHUB_DEFAULT_REDIRECT_URL
        sync: false
      - key: LEETCODE_API_BASE_URL
        value: https://leetcode-stats-api.herokuapp.com
      - key: ENABLE_CRON
        value: false

databases:
  - name: skillsync-db
    plan: starter
    databaseName: skillsync
    user: skillsync

